# Generated by Django 3.1.3 on 2020-11-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
