# Generated by Django 3.1.3 on 2020-11-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokeinfo', '0002_auto_20201120_0148'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evolution',
            unique_together={('poke_id', 'id_evolution')},
        ),
        migrations.AlterUniqueTogether(
            name='stats',
            unique_together={('poke_id', 'stat_name')},
        ),
    ]
